---
title: "Intro to `distplyr`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro to `distplyr`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Point predictions can only get you so far. Usually, we want more than just a single best guess, but some depiction of the spread of probable outcomes. Distributions can help with this, and `distplyr` gives you a means of working with distributions. 

`distplyr` makes it easy for you to:

- Make a distribution (parametric or not), such as a Poisson distribution or empirical distribution.
- Evaluate or extract various functions representing a distribution, such as a cdf or hazard function.
- Evaluate properties of a distribution, such as mean, variance, extreme value index, etc.
- Manipulate distributions, such as by mixing or grafting, to obtain a new distribution.

`distplyr` is _not_ a modelling package, meaning it won't optimize a distribution's fit to data.  

## Making a Distribution

Making a distribution will probably most commonly involve making either a parametric distribution or a step distribution. You can also make your own.
